### ISSUE TITLE
Command failing after `nx migrate latest`

### ISSUE THREAD

**Issue by LuckeeDev** [jscutlery/semver#189]
After migrating to the latest version of the NX suite, if I try to run `nx run workspace:version` I get this error:
```
"BuilderInputSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"BuilderOutputSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
schema with key or id "http://json-schema.org/draft-07/schema" already exists
```

`@jscutlery/semver` version is 2.1.0.

Any idea about how to solve this?

**Comment by edbzn** [comment]
Hi @LuckeeDev, this problem was resolved in version `2.2.0`, thanks for reporting!

**Comment by LuckeeDev** [comment]
Love it! Thanks for the awesome work @edbzn

**Comment by mtrefzer** [comment]
After deleting the `node_modules` folder and rerunning `npm i`.
I still get the error with the version `2.2.0`
```
> nx run workspace:version --version=minor 
schema with key or id "http://json-schema.org/draft-07/schema" already exists
```
Any Ideas? All my used dependencies are:
```
"dependencies": {
    "@angular/animations": "12.0.0",
    "@angular/common": "12.0.0",
    "@angular/compiler": "12.0.0",
    "@angular/core": "12.0.0",
    "@angular/forms": "12.0.0",
    "@angular/platform-browser": "12.0.0",
    "@angular/platform-browser-dynamic": "12.0.0",
    "@angular/router": "12.0.0",
    "@datorama/akita": "^6.1.3",
    "@mdi/font": "^5.9.55",
    "@nestjs/common": "7.6.15",
    "@nestjs/config": "0.6.3",
    "@nestjs/core": "7.6.15",
    "@nestjs/jwt": "7.2.0",
    "@nestjs/passport": "7.1.5",
    "@nestjs/platform-express": "7.6.15",
    "@nestjs/schedule": "0.4.3",
    "@nestjs/serve-static": "2.1.4",
    "@ngneat/transloco": "^2.20.1",
    "@ngneat/until-destroy": "^8.0.4",
    "@nrwl/angular": "12.3.3",
    "@prisma/client": "^2.22.1",
    "@rx-angular/cdk": "^1.0.0-alpha.8",
    "@rx-angular/template": "^1.0.0-beta.25",
    "bcryptjs": "2.4.3",
    "class-transformer": "0.4.0",
    "class-validator": "0.13.1",
    "compression": "^1.7.4",
    "cookie-parser": "1.4.5",
    "express": "^4.17.1",
    "helmet": "4.6.0",
    "joi": "^17.4.0",
    "nodemailer": "6.6.0",
    "passport": "0.4.1",
    "passport-jwt": "4.0.0",
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primeng": "^11.4.1",
    "rand-token": "1.0.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "12.0.0-beta.0",
    "@angular-devkit/build-angular": "12.0.0",
    "@angular-eslint/eslint-plugin": "12.0.0",
    "@angular-eslint/eslint-plugin-template": "12.0.0",
    "@angular-eslint/template-parser": "12.0.0",
    "@angular/cli": "12.0.0",
    "@angular/compiler-cli": "12.0.0",
    "@angular/language-service": "12.0.0",
    "@commitlint/cli": "^12.1.1",
    "@commitlint/config-conventional": "^12.1.3",
    "@jscutlery/semver": "^2.2.0",
    "@nestjs/schematics": "^7.3.1",
    "@nestjs/testing": "^7.6.15",
    "@nguniversal/builders": "^12.0.0",
    "@nrwl/cli": "12.3.3",
    "@nrwl/cypress": "12.3.3",
    "@nrwl/eslint-plugin-nx": "12.3.3",
    "@nrwl/jest": "12.3.3",
    "@nrwl/linter": "12.3.3",
    "@nrwl/nest": "12.3.3",
    "@nrwl/node": "12.3.3",
    "@nrwl/tao": "12.3.3",
    "@nrwl/workspace": "12.3.3",
    "@types/bcryptjs": "^2.4.2",
    "@types/compression": "^1.7.0",
    "@types/cookie-parser": "^1.4.2",
    "@types/express": "^4.17.0",
    "@types/jest": "26.0.8",
    "@types/node": "14.14.33",
    "@types/nodemailer": "^6.4.1",
    "@types/passport": "1.0.6",
    "@types/passport-jwt": "3.0.5",
    "@types/supertest": "2.0.11",
    "@types/validator": "13.1.3",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.3.0",
    "cross-env": "^7.0.3",
    "cypress": "^6.0.1",
    "dotenv": "8.2.0",
    "eslint": "7.10.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "husky": "^6.0.0",
    "import-conductor": "^2.2.5",
    "jest": "26.2.2",
    "jest-preset-angular": "8.4.0",
    "lint-staged": "^10.5.4",
    "postcss": "^8.2.15",
    "prettier": "2.2.1",
    "prisma": "^2.22.1",
    "tailwindcss": "^2.1.2",
    "ts-jest": "26.5.5",
    "ts-node": "~9.1.1",
    "typescript": "4.2.4"
  }
```

**Comment by edbzn** [comment]
Oh my bad, good catch @mtrefzer, it's fixed, it will be published today.

**Comment by mtrefzer** [comment]
Perfect now everything is back to normal and thank you for your amazing work  @edbzn
